CREATE TABLE `team` (
     id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '팀 ID',
     name VARCHAR(36) DEFAULT 'name' NOT NULL COMMENT '팀 이름',
     p_id INT NOT NULL DEFAULT '0' COMMENT '팀 유형 ID'
) COMMENT '팀';

ALTER TABLE `team` ADD FOREIGN KEY (p_id) REFERENCES `team`(id)